
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-hostpath
spec:
  rules:
  - name: block-hostpath
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "hostPath volumes are not allowed"
      pattern:
        spec:
          volumes:
            - not:
                hostPath: "?*"
