
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: secure-demo
type: Opaque
stringData:
  username: admin
  password: "S3cureP@ssw0rd!"
---
# Pod consuming secret as env
apiVersion: v1
kind: Pod
metadata:
  name: secret-consumer
  namespace: secure-demo
spec:
  containers:
  - name: app
    image: alpine:3.18
    command: ["sh","-c","sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
