
apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limits
  namespace: secure-demo
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
---
# ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-demo
  namespace: secure-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
